//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmaDomain
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicament
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Medicament()
        {
            this.StockMedis = new HashSet<StockMedi>();
            this.VenteMedis = new HashSet<VenteMedi>();
        }
    
        public int CodeMedicament { get; set; }
        public string LibelleMedicament { get; set; }
        public decimal Prix { get; set; }
        public int CodeFamille { get; set; }
    
        public virtual Famille Famille { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StockMedi> StockMedis { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VenteMedi> VenteMedis { get; set; }
    }
}
